---
inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - _misc/*
    - bin/*
    - vendor/**/*
  NewCops: enable

Lint/UnusedMethodArgument:
  Exclude:
    - lib/prawn_html/utils.rb

Naming/FileName:
  Exclude:
    - lib/prawn-html.rb

Naming/MethodParameterName:
  Exclude:
    - lib/prawn_html/pdf_wrapper.rb

RSpec/ExampleLength:
  # default: 5
  Max: 10

RSpec/MultipleMemoizedHelpers:
  # default: 5
  Max: 6
